[Bug Fix]: form submission not working for radio, checkbox
adobe/afb pull request #8
Opened 2023-05-04 10:08 UTC by neerajadobe93

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--<repo>--<owner>.hlx.page/
- After: https://<branch>--<repo>--<owner>.hlx.page/

2023-05-04 11:12 UTC, vdua commented on blocks/form/form.js
> +      payload[fe.name] = fe.value;
the check for fe.name should be the first check

```
if (fe.name) {
   if (fe.type === 'radio' && fe.checked) {
         payload[fe.name] = fe.value
   } else if (fe.type === 'checkox' && fe.checked) { .... }
   else {
       ...
   }
}
```

2023-05-04 11:12 UTC, vdua requested changes
Please fix lint issues and look at my comment.

2023-05-04 14:29 UTC, neerajadobe93 commented on blocks/form/form.js
> +      payload[fe.name] = fe.value;
@vdua  i think name field is required for every input field, so ideally it should fail if name is undefined ? please correct if my understanding is correct

2023-05-04 15:38 UTC, neerajadobe93 commented on blocks/form/form.js
> +      payload[fe.name] = fe.value;
lint issues are fixed with form.js file. varun , i am seeing multiple lint issues as well with other blocks. i am using  airbnb-base-eslint config.

2023-05-05 06:37 UTC, vdua commented on blocks/form/form.js
> +      payload[fe.name] = fe.value;
> i think name field is required for every input field
No that is not correct. Consider buttons, output, etc. elements. 

I was just saying that check for `fe.name` that is there in [Line 10](https://github.com/adobe/afb/pull/8/files#diff-14d0faad899dcfcb4e5cd318658f4d58b9e2aa66ebc5912bbe09302339f6a564R10) should be moved up.

2023-05-05 07:23 UTC, vdua approved these changes
LGTM and as discussed please update the if check for fe.name and merge.

2023-05-05 07:32 UTC, neerajadobe93 commented
@vdua  can you please merge this PR as i don't have write access

2023-06-07 03:46 UTC, closed without merging